### ISSUE TITLE
Playground (electron) does not work with local webservers.

### ISSUE THREAD

**Issue by buehler** [prismagraphql/graphql-playground#599] opened 2018-03-14 09:53 UTC
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
macOS 10.13.3

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.4.4

#### What is the expected behavior?

That I can query something locally.

#### What is the actual behavior?

```
Error: only http(s) protocols are supported
    at file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.5ea3069b9949ed4ad38f.js:65330:10
    at Promise (<anonymous>)
    at new Fetch (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.5ea3069b9949ed4ad38f.js:65321:9)
    at Fetch 
```

#### What steps may we take to reproduce the behavior?

I started a webserver (.net core with graphQL.net) on localhost:5000/. When I use the GraphiQL app (also electron app) and enter http://localhost:5000/ as endpoint, it works like a charm. When I do the same with the graphql-playground app, I just get the message that the server cannot be reached.

**Comment by timsuchanek** [comment] 2018-05-29 12:34
Thanks for reporting @buehler. I'm using the Playground quite often with local projects, but couldn't reproduce that until now. Is this still the case in the latest version?

**Comment by timsuchanek** [comment] 2018-06-17 11:47
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!

**Closed by timsuchanek** 2018-06-17 11:47 UTC
Labels: bug
